In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Dataset 1 - Purchases Data

In [2]:
file_path = "C://Users//vaish//Desktop//MKT 4990//purchases.csv"
purchases = pd.read_csv(file_path)

In [3]:
purchases.shape

(1839075, 10)

### Dataset 2 - Users/Survey Data

In [4]:
file_path2 = "C://Users//vaish//Desktop//MKT 4990//Datasets//survey.csv"
users = pd.read_csv(file_path2)

### Preprocessing Purchases Dataset

In [5]:
purchases.head()

,User ID,Product ID,Category,Title,Quantity,Purchase Price Per Unit,State,Order Date,Duplicate,Brand
0,R_01vNIayewjIIKMF,B0143RTB1E,FLASH_MEMORY,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,1.0,7.98,NJ,2018-12-04,No,SanDisk Ultra
1,R_01vNIayewjIIKMF,B01MA1MJ6H,HEADPHONES,Betron BS10 Earphones Wired Headphones in Ear ...,1.0,13.99,NJ,2018-12-22,No,Betron BS10
2,R_01vNIayewjIIKMF,B078JZTFN3,Unknown,Unknown,1.0,8.99,NJ,2018-12-24,No,unknown
3,R_01vNIayewjIIKMF,B06XWF9HML,DISHWARE_BOWL,Perfecto Stainless Steel Shaving Bowl. Durable...,1.0,10.45,NJ,2018-12-25,No,Perfecto Stainless
4,R_01vNIayewjIIKMF,B00837ZOI0,SHAVING_AGENT,Proraso Shaving Cream for Men,1.0,10.00,NJ,2018-12-25,No,Proraso Shaving

In [6]:
purchases.rename(columns={'User ID': 'User_ID', 'Product ID	':'Product_ID','Shipping Address State':'State','brand':'Brand'}, inplace=True)

In [7]:
purchases.isnull().sum()

User_ID                      0
Product ID                   0
Category                     0
Title                        0
Quantity                     0
Purchase Price Per Unit      0
State                        0
Order Date                   0
Duplicate                    0
Brand                      982
dtype: int64

In [8]:
purchases["Order Date"] = pd.to_datetime(purchases["Order Date"], errors="coerce")
purchases = purchases.dropna(subset=["Order Date"])

In [9]:
purchases["Year"]= purchases["Order Date"].dt.year
purchases["Month"]= purchases["Order Date"].dt.strftime('%b')
purchases["Day"]= purchases["Order Date"].dt.day
purchases = purchases.drop(columns= ["Order Date"])

In [10]:
purchases.head()

,User_ID,Product ID,Category,Title,Quantity,Purchase Price Per Unit,State,Duplicate,Brand,Year,Month,Day
0,R_01vNIayewjIIKMF,B0143RTB1E,FLASH_MEMORY,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,1.0,7.98,NJ,No,SanDisk Ultra,2018,Dec,4
1,R_01vNIayewjIIKMF,B01MA1MJ6H,HEADPHONES,Betron BS10 Earphones Wired Headphones in Ear ...,1.0,13.99,NJ,No,Betron BS10,2018,Dec,22
2,R_01vNIayewjIIKMF,B078JZTFN3,Unknown,Unknown,1.0,8.99,NJ,No,unknown,2018,Dec,24
3,R_01vNIayewjIIKMF,B06XWF9HML,DISHWARE_BOWL,Perfecto Stainless Steel Shaving Bowl. Durable...,1.0,10.45,NJ,No,Perfecto Stainless,2018,Dec,25
4,R_01vNIayewjIIKMF,B00837ZOI0,SHAVING_AGENT,Proraso Shaving Cream for Men,1.0,10.00,NJ,No,Proraso Shaving,2018,Dec,25

In [11]:
purchases.duplicated().any()

False

In [12]:
purchases.shape

(1839075, 12)

### Preprocessing Survey/Users Dataset

In [13]:
users.head()

,Survey ResponseID,Q-demos-age,Q-demos-hispanic,Q-demos-race,Q-demos-education,Q-demos-income,Q-demos-gender,Q-sexual-orientation,Q-demos-state,Q-amazon-use-howmany,...,Q-substance-use-marijuana,Q-substance-use-alcohol,Q-personal-diabetes,Q-personal-wheelchair,Q-life-changes,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society
0,R_1ou69fj4DQGsVcp,35 - 44 years,No,Black or African American,High school diploma or GED,"$25,000 - $49,999",Female,heterosexual (straight),Iowa,2,...,No,Yes,No,No,Lost a job,No,No,No,No,No
1,R_2UbJL30HRjK1sdD,45 - 54 years,No,White or Caucasian,High school diploma or GED,"$100,000 - $149,999",Male,heterosexual (straight),Ohio,2,...,No,No,No,No,NaN,No,No,No,No,Yes
2,R_UPXamGKtmf4RVIZ,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,heterosexual (straight),Arkansas,1 (just me!),...,No,No,Yes,No,NaN,No,No,No,No,Yes
3,R_2dYk5auG9Fv5Qve,35 - 44 years,Yes,White or Caucasian,"Graduate or professional degree (MA, MS, MBA, ...","$50,000 - $74,999",Male,heterosexual (straight),Tennessee,1 (just me!),...,No,No,No,No,NaN,No,No,No,No,No
4,R_2aP0GyIR66gSTiR,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$50,000 - $74,999",Male,heterosexual (straight),Virginia,2,...,No,Yes,No,No,NaN,No,Yes if consumers get part of the profit,I don't know,No,No

In [14]:
users.columns

Index(['Survey ResponseID', 'Q-demos-age', 'Q-demos-hispanic', 'Q-demos-race',
       'Q-demos-education', 'Q-demos-income', 'Q-demos-gender',
       'Q-sexual-orientation', 'Q-demos-state', 'Q-amazon-use-howmany',
       'Q-amazon-use-hh-size', 'Q-amazon-use-how-oft',
       'Q-substance-use-cigarettes', 'Q-substance-use-marijuana',
       'Q-substance-use-alcohol', 'Q-personal-diabetes',
       'Q-personal-wheelchair', 'Q-life-changes', 'Q-sell-YOUR-data',
       'Q-sell-consumer-data', 'Q-small-biz-use', 'Q-census-use',
       'Q-research-society'],
      dtype='object')

In [15]:
users.rename(columns={'Survey ResponseID': 'User_ID', 'Q-demos-age':'Age','Q-demos-hispanic':'Hispanic','Q-demos-race':'Race','Q-demos-education':'Education',
                      'Q-demos-state':'State','Q-demos-income':'Income','Q-demos-gender':'Gender','Q-sexual-orientation':'Sexual_Orientation','Q-amazon-use-howmany':'No.of Users',
                      'Q-amazon-use-hh-size':'Family Size','Q-amazon-use-how-oft':'Acc Usage', 'Q-substance-use-cigarettes':'Cigarettes','Q-substance-use-marijuana':'Marijuana',
                      'Q-substance-use-alcohol':'Alcohol', 'Q-personal-diabetes':'Diabetes', 'Q-personal-wheelchair':'Wheel_Chair','Q-life-changes':'Life_Changes',
                      'Q-sell-YOUR-data':'Sell_Data','Q-sell-consumer-data':'Sell_Consumer_Data','Q-small-biz-use':'Small_Business_Use','Q-census-use':'Census_Use',
                      'Q-research-society':'Research'
                      }, inplace=True)

In [16]:
users.head()

,User_ID,Age,Hispanic,Race,Education,Income,Gender,Sexual_Orientation,State,No.of Users,...,Marijuana,Alcohol,Diabetes,Wheel_Chair,Life_Changes,Sell_Data,Sell_Consumer_Data,Small_Business_Use,Census_Use,Research
0,R_1ou69fj4DQGsVcp,35 - 44 years,No,Black or African American,High school diploma or GED,"$25,000 - $49,999",Female,heterosexual (straight),Iowa,2,...,No,Yes,No,No,Lost a job,No,No,No,No,No
1,R_2UbJL30HRjK1sdD,45 - 54 years,No,White or Caucasian,High school diploma or GED,"$100,000 - $149,999",Male,heterosexual (straight),Ohio,2,...,No,No,No,No,NaN,No,No,No,No,Yes
2,R_UPXamGKtmf4RVIZ,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,heterosexual (straight),Arkansas,1 (just me!),...,No,No,Yes,No,NaN,No,No,No,No,Yes
3,R_2dYk5auG9Fv5Qve,35 - 44 years,Yes,White or Caucasian,"Graduate or professional degree (MA, MS, MBA, ...","$50,000 - $74,999",Male,heterosexual (straight),Tennessee,1 (just me!),...,No,No,No,No,NaN,No,No,No,No,No
4,R_2aP0GyIR66gSTiR,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$50,000 - $74,999",Male,heterosexual (straight),Virginia,2,...,No,Yes,No,No,NaN,No,Yes if consumers get part of the profit,I don't know,No,No

In [17]:
users.isnull().sum()

User_ID                  0
Age                      0
Hispanic                 0
Race                     0
Education                0
Income                   0
Gender                   0
Sexual_Orientation       0
State                    0
No.of Users              0
Family Size              0
Acc Usage                0
Cigarettes               0
Marijuana                0
Alcohol                  0
Diabetes                 0
Wheel_Chair              0
Life_Changes          3384
Sell_Data                0
Sell_Consumer_Data       0
Small_Business_Use       0
Census_Use               0
Research                 0
dtype: int64

In [18]:
users['Life_Changes'] = users['Life_Changes'].fillna("N/A")

In [19]:
users.isnull().sum()

User_ID               0
Age                   0
Hispanic              0
Race                  0
Education             0
Income                0
Gender                0
Sexual_Orientation    0
State                 0
No.of Users           0
Family Size           0
Acc Usage             0
Cigarettes            0
Marijuana             0
Alcohol               0
Diabetes              0
Wheel_Chair           0
Life_Changes          0
Sell_Data             0
Sell_Consumer_Data    0
Small_Business_Use    0
Census_Use            0
Research              0
dtype: int64

In [20]:
users.duplicated().any()

False

In [22]:
purchases["User_ID"].nunique()

5026

In [23]:
users["User_ID"].nunique()

5027

### Merging 2 Datasets

In [24]:
combined = pd.merge(purchases, users, on='User_ID', how='inner')

In [25]:
combined.shape

(1839075, 34)

In [26]:
combined["User_ID"].nunique()

5026

In [27]:
combined.head(5)

,User_ID,Product ID,Category,Title,Quantity,Purchase Price Per Unit,State_x,Duplicate,Brand,Year,...,Marijuana,Alcohol,Diabetes,Wheel_Chair,Life_Changes,Sell_Data,Sell_Consumer_Data,Small_Business_Use,Census_Use,Research
0,R_01vNIayewjIIKMF,B0143RTB1E,FLASH_MEMORY,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,1.0,7.98,NJ,No,SanDisk Ultra,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
1,R_01vNIayewjIIKMF,B01MA1MJ6H,HEADPHONES,Betron BS10 Earphones Wired Headphones in Ear ...,1.0,13.99,NJ,No,Betron BS10,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
2,R_01vNIayewjIIKMF,B078JZTFN3,Unknown,Unknown,1.0,8.99,NJ,No,unknown,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
3,R_01vNIayewjIIKMF,B06XWF9HML,DISHWARE_BOWL,Perfecto Stainless Steel Shaving Bowl. Durable...,1.0,10.45,NJ,No,Perfecto Stainless,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
4,R_01vNIayewjIIKMF,B00837ZOI0,SHAVING_AGENT,Proraso Shaving Cream for Men,1.0,10.00,NJ,No,Proraso Shaving,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes

In [28]:
combined.columns

Index(['User_ID', 'Product ID', 'Category', 'Title', 'Quantity',
       'Purchase Price Per Unit', 'State_x', 'Duplicate', 'Brand', 'Year',
       'Month', 'Day', 'Age', 'Hispanic', 'Race', 'Education', 'Income',
       'Gender', 'Sexual_Orientation', 'State_y', 'No.of Users', 'Family Size',
       'Acc Usage', 'Cigarettes', 'Marijuana', 'Alcohol', 'Diabetes',
       'Wheel_Chair', 'Life_Changes', 'Sell_Data', 'Sell_Consumer_Data',
       'Small_Business_Use', 'Census_Use', 'Research'],
      dtype='object')

### Preprocessing of Merged Dataset

In [29]:
state_map = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
    "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
    "District of Columbia": "DC", "Florida": "FL", "Georgia": "GA",
    "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL", "Indiana": "IN",
    "Iowa": "IA", "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA",
    "Maine": "ME", "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI",
    "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO", "Montana": "MT",
    "Nebraska": "NE", "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ",
    "New Mexico": "NM", "New York": "NY", "North Carolina": "NC",
    "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK", "Oregon": "OR",
    "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC",
    "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT",
    "Vermont": "VT", "Virginia": "VA", "Washington": "WA",
    "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY",
    "American Samoa": "AS", "Guam": "GU", "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR", "Virgin Islands": "VI", "Trust Territories": "TT"
}

In [30]:
combined["State_y"] = combined["State_y"].replace(state_map)

In [31]:
combined["State_y"]

0          NJ
1          NJ
2          NJ
3          NJ
4          NJ
           ..
1839070    MA
1839071    MA
1839072    MA
1839073    MA
1839074    MA
Name: State_y, Length: 1839075, dtype: object

In [32]:
combined["State_x"].equals(combined["State_y"])

False

In [33]:
matches = combined["State_x"] == combined["State_y"]

In [34]:
matches

0           True
1           True
2           True
3           True
4           True
           ...
1839070     True
1839071     True
1839072     True
1839073     True
1839074    False
Length: 1839075, dtype: bool

In [35]:
matches.value_counts()

True     1598864
False     240211
Name: count, dtype: int64

In [36]:
combined.rename(columns={'State_x':'Order_State','State_y':'State'})

,User_ID,Product ID,Category,Title,Quantity,Purchase Price Per Unit,Order_State,Duplicate,Brand,Year,...,Marijuana,Alcohol,Diabetes,Wheel_Chair,Life_Changes,Sell_Data,Sell_Consumer_Data,Small_Business_Use,Census_Use,Research
0,R_01vNIayewjIIKMF,B0143RTB1E,FLASH_MEMORY,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,1.0,7.98,NJ,No,SanDisk Ultra,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
1,R_01vNIayewjIIKMF,B01MA1MJ6H,HEADPHONES,Betron BS10 Earphones Wired Headphones in Ear ...,1.0,13.99,NJ,No,Betron BS10,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
2,R_01vNIayewjIIKMF,B078JZTFN3,Unknown,Unknown,1.0,8.99,NJ,No,unknown,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
3,R_01vNIayewjIIKMF,B06XWF9HML,DISHWARE_BOWL,Perfecto Stainless Steel Shaving Bowl. Durable...,1.0,10.45,NJ,No,Perfecto Stainless,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
4,R_01vNIayewjIIKMF,B00837ZOI0,SHAVING_AGENT,Proraso Shaving Cream for Men,1.0,10.00,NJ,No,Proraso Shaving,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1839070,R_zfqnsBzlOAKibzb,B015ZRTHVA,TOOTH_CLEANING_AGENT,Tanner's Tasty Paste Vanilla Bling - Anticavit...,1.0,6.99,MA,No,Tanners Tasty,2021,...,No,No,No,Yes,N/A,No,No,Yes,I don't know,Yes
1839071,R_zfqnsBzlOAKibzb,B00QGCXPRG,TOWEL,Sinland Microfiber Cleaning Cloth Dish Cloth K...,1.0,15.99,MA,No,Sinland Microfiber,2021,...,No,No,No,Yes,N/A,No,No,Yes,I don't know,Yes
1839072,R_zfqnsBzlOAKibzb,B015ZRTHVA,TOOTH_CLEANING_AGENT,Tanner's Tasty Paste Vanilla Bling - Anticavit...,4.0,6.99,MA,No,Tanners Tasty,2021,...,No,No,No,Yes,N/A,No,No,Yes,I don't know,Yes
1839073,R_zfqnsBzlOAKibzb,B015ZRTHVA,TOOTH_CLEANING_AGENT,Tanner's Tasty Paste Vanilla Bling - Anticavit...,4.0,6.99,MA,No,Tanners Tasty,2021,...,No,No,No,Yes,N/A,No,No,Yes,I don't know,Yes
1839074,R_zfqnsBzlOAKibzb,1441337652,ABIS_BOOK,Wild Mystic Oracle Card Deck: A 50-Card Deck a...,1.0,19.99,Unknown,No,Wild Mystic,2022,...,No,No,No,Yes,N/A,No,No,Yes,I don't know,Yes

In [37]:
combined["Category"].nunique()

1872

In [38]:
unique_category = combined["Category"].value_counts()

In [39]:
unique_category

Category
Unknown                          89200
ABIS_BOOK                        87153
PET_FOOD                         37970
SHIRT                            27143
NUTRITIONAL_SUPPLEMENT           26790
                                 ...
TEACHING_AND_SCHOOL_SUPPLIES         1
CAMERA_POWER_SUPPLY                  1
SPORT_POM_POM                        1
POWERSPORTS_RIDING_JACKET            1
COMPUTER_VIDEO_GAME_CONTOLLER        1
Name: count, Length: 1872, dtype: int64

### Combining Categories

#### Electronics

In [40]:

electronics_keywords = [
    "ELECTRON", "PHONE", "MOBILE", "SMARTPHONE", "TABLET",
    "LAPTOP", "COMPUTER", "PC", "KEYBOARD", "MOUSE", "MONITOR",
    "PRINTER", "ROUTER", "MODEM", "USB", "CABLE", "ADAPTER",
    "CHARGER", "BATTER", "POWER", "HEADPHONE", "EARPHONE","ALARM", "KEYCAP", "CORD_MANAGEMENT_COVER",
    "SPEAKER", "AUDIO", "MIC", "CAMERA", "TV", "TELEVISION","SEXUAL_STIMULATION_DEVICE",
    "VIDEO", "PROJECTOR", "DRONE", "GPS", "SMARTWATCH","FAN",
    "WATCH", "CONSOLE", "GAME", "SSD", "HARD_DRIVE","ACCELERATION_SENSOR",
    "MEMORY", "FLASH","ELECTRIC","DIGITAL","SCREEN_PROTECTOR",
    "FLASH_MEMORY","CHARGING_ADAPTER","POWER_STRIP","LIGHT_BULB",
    "MULTIPORT_HUB","CAMCORDER","VDO_DEVICES","ANTENNA","VIRTUAL_REALITY_HEADSET",
    "WIRELESS_SIGNAL_REPEATER","TWO_WAY_RADIO","RADIO","OPTICAL_DISC_DRIVE",
    "AMAZON_DEVICE","NETWORKING_DEVICE","AV_RECEIVER","SURVEILANCE_SYSTEMS","WEATHER_STATION",
    "CAPACITOR","RELAY","PROJECTION_SCREEN","SCANNER","INTEGRATED_STEREO_SYSTEM","MOTION_DETECTOR_DEVICE",
    "RANGEFINDER","TUNER","WEBCAM","PA_SYSTEM","SECURITY_SYSTEM","RADAR_DETECTOR","ABIS_WIRELESS","WIRELESS_DEVICE","SATELLITE_RECEIVER",
    "MULTIFUNCTION_DEVICE","FSN_DEVICES","Blu-ray","SATELLITE_OR_DSS","VCR"
]


pattern = "|".join(electronics_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Electronics"

In [41]:
combined["Category"].value_counts().head()

Category
Electronics    246994
Unknown         89200
ABIS_BOOK       87153
PET_FOOD        37970
SHIRT           27143
Name: count, dtype: int64

#### Home-Bed-Bath

In [42]:
home_keywords = [
    "COMFORTER","BATH","KITCHEN", "UTENSIL",
    "LIGHTING", "LAMP","BASKET","SWING","TRAY","FITTED_SHEET",
    "ORGANIZER","HOME", "FURNITURE", "SOFA", "CHAIR", "TABLE", "DESK",
    "BED", "MATTRESS", "PILLOW", "BLANKET", "BEDSHEET",
    "CURTAIN", "CARPET", "RUG", "DECOR", "LAMP", "LIGHT",
    "KITCHEN", "COOKWARE", "UTENSIL", "PAN", "POT",
    "DISH", "PLATE", "BOWL", "CUP", "GLASS",
    "APPLIANCE", "MICROWAVE", "REFRIGERATOR", "OVEN",
    "VACUUM", "CLEAN", "STORAGE", "CABINET",
    "BATH", "TOWEL", "SHOWER", "MIRROR",
    "GARDEN", "PLANT", "OUTDOOR", "TOOLS",  "CANDLE",
    "WALL_ART","FIGURINE","TOILET","HANGING_ORNAMENT",
    "PICTURE_FRAME", "SHELF","RUG","INCENSE", "INCENSE_HOLDER", "FOUNTAIN",
    "AREA_DEODORIZER","CADDY","BOTTLE","FITT,ED_SHEET",
    "BACKDROP","SCULPTURE","VIVARIUM","WINDOW_SHADE","STOOL_SEATING",
    "OTTOMAN","WIND_CHIME","GARLAND","VASE","BENCH","FLAT_SHEET","HEADBOARD",
    "MAILBOX","RAMP","DUVET_COVER","FIREPLACE","SNOW_GLOBE","GLOBE","URN",
    "OUTBUILDING","AWNING","FIRE_SCREEN","FLOOR_COVER","FREEZER"
]

pattern = "|".join(home_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Home-Bed-Bath"

In [43]:
combined["Category"].value_counts().head()

Category
Home-Bed-Bath    305711
Electronics      246994
Unknown           89200
ABIS_BOOK         87153
PET_FOOD          37970
Name: count, dtype: int64

#### Clothing

In [44]:
clothing_keywords = [
    "SWEATSHIRT", "ACTIVEWEAR","SWIMWEAR",
    "UNIFORM","INNERWEAR","NIGHTWEAR", "SLEEPWEAR",
    "CLOTHING", "APPAREL", "FASHION","CORSET",
    "SHIRT", "T-SHIRT", "TSHIRT", "TOP", "BLOUSE",
    "PANT", "JEAN", "TROUSER", "SHORT",
    "DRESS", "SKIRT","OUTERWEAR","VEST","UNDERGARMENT_THIGH_SLIMMER",
    "JACKET", "COAT", "HOODIE", "SWEATER",
    "SUIT", "BLAZER","ETHNIC_WEAR","DUPATTA", "HAT",
    "LEOTARD","TUNIC","SANDAL","BOOT","KURTA",
    "UNDERWEAR", "BRA", "LINGERIE", "SOCK",
    "SCARF","GLOVE","KIDS_WEAR","BABY_WEAR","PAJAMAS","CLOTHES","TIGHTS",
    "HANDBAG","WALLET","COORDINATED_OUTFIT","ROBE","WAIST_PACK","TOTE_BAG","WAIST_CINCHER",
    "UTILITY_HOLSTER_POUCH","APRON","NECKTIE","OVERALLS","ARM_SLEEVE","LEG_SLEEVE",
    "GARMENT_PROTECTOR_COVER","COIN_PURSE_POUCH","EYEWEAR","BELTS","SAREE","KIMONO",
    "CHOLI","FOOTWEAR","SASH","BODYSTOCKING","CLOTH_WRAP"
]
pattern = "|".join(clothing_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Clothing"

In [45]:
combined["Category"].value_counts().head()

Category
Home-Bed-Bath    305711
Electronics      246994
Clothing         143919
Unknown           89200
ABIS_BOOK         87153
Name: count, dtype: int64

#### Beauty

In [46]:
beauty_keywords = [
    "BEAUTY","SKIN", "SKINCARE", "FACE", "FACIAL", "CREAM", "CLEANSER",
    "MOISTURIZER", "SERUM", "TONER", "SUNSCREEN", "SPF",
    "LOTION", "SCRUB", "MASK", "ACNE", "ANTI_AGING", "WRINKLE",
    "EYE_CREAM","BODY_LUBRICANT","DRYER","MAKE_UP",

    "MAKEUP", "FOUNDATION", "CONCEALER", "POWDER", "BLUSH",
    "BRONZER", "HIGHLIGHTER", "LIP", "LIPSTICK", "LIP_GLOSS",
    "LIP_BALM", "MASCARA", "EYELINER", "EYESHADOW", "BROW",
    "NAIL", "NAIL_POLISH", "NAIL_LACQUER","TOOTH_WHITENER",
    "FALSE_EYELASH","SELF_TANNER",
    "TEMPORARY_TATTOO","DYE","COTTON_PAD","CUTICLE_PUSHER"

    "HAIR", "SHAMPOO", "CONDITIONER", "HAIR_OIL", "HAIR_SERUM",
    "HAIR_SPRAY", "HAIR_COLOR", "HAIR_DYE", "HAIR_MASK",
    "HAIR_TREATMENT", "STYLING", "GEL",

    "PERFUME", "COLOGNE", "FRAGRANCE", "DEODORANT",
    "BODY_SPRAY", "MIST","HAIR_TIE","HAIR_COMB","HAIR_REMOVAL_AGENT","HAIR_TRIMMING_KIT","CUTICLE_PUSHER",

    "SOAP", "BODY_WASH", "BODY_LOTION", "HAND_CREAM",
    "FOOT_CREAM", "SHAVING", "RAZOR", "AFTERSHAVE",
    "GROOMING", "ORAL", "TOOTHPASTE", "TOOTHBRUSH",
    "MOUTHWASH",

    "MAKEUP_BRUSH", "COSMETIC", "BEAUTY_TOOL", "TWEEZER",
    "CURLER", "STRAIGHTENER", "HAIR_DRYER", "TRIMMER",
    "EPILATOR", "EYELID_COLOR",
    "WIG","HAIR_STYLING_AGENT","SKIN_TREATMENT_MASK",
    "BODY_LUBRICANT","TOOTH_CLEANING_AGENT"
    
]

pattern = "|".join(beauty_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Beauty"

#### Food

In [47]:
food_keywords = [
    "FOOD", "GROCERY", "EDIBLE", "PANTRY","WINE",
    "FRUIT", "VEGETABLE", "VEGGIE", "PRODUCE","BEER",
    "MILK", "CHEESE", "BUTTER", "YOGURT", "CREAM", "DAIRY",
    "MEAT", "BEEF", "CHICKEN", "POULTRY", "PORK", "FISH",
    "SEAFOOD", "TURKEY", "SAUSAGE", "BACON", "EGG",
    "BREAD", "BUN", "CAKE", "COOKIE", "BISCUIT",
    "PASTRY", "MUFFIN", "CRACKER","TOFU","VINE","PIE","COCKTAIL",
    "SNACK", "CHIP", "NUT", "POPCORN", "CANDY",
    "CHOCOLATE", "BAR", "GRANOLA","HONEY","PIZZA",
    "DRINK", "BEVERAGE", "JUICE", "SODA", "SOFT_DRINK",
    "COFFEE", "TEA", "ENERGY_DRINK", "WATER",
    "SOUP", "NOODLE", "PASTA", "RICE", "CEREAL",
    "SAUCE", "KETCHUP", "MAYO", "SPICE","THICKENING_AGENT",
    "LEAVENING_AGENT",
    "SEASONING", "CONDIMENT","VINEGAR","PICKLE",
    "FROZEN", "ICE_CREAM","CHEWING_GUM","SUGAR",
    "ORGANIC", "GLUTEN", "PROTEIN_BAR","ESSENTIAL_OIL","BAKING","LEGUME",
    "JERKY","SYRUP","DAIRY_BASED_CHEESE","BREAD","CRACKER","PACKAGED_SOUP_AND_STEW",
    "POULTRY","HERB","MEAT","FRUIT","OLIVE", "FLOUR",
    "PRETZEL","CULINARY_SALT","CULINARY_MUSHROOM","SPIRITS",
    "PREPARED_DOUGH","TEMPEH","FUDGE","RELISH","EXTRACT"
]
pattern = "|".join(food_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Food"

#### Sports

In [48]:
sports_keywords = [
    "SPORT", "SPORTS", "ATHLETIC", "FITNESS", "WORKOUT","EXERCISE", "TRAINING",
    "DUMBBELL", "BARBELL", "WEIGHT", "KETTLEBELL",
    "TREADMILL", "ELLIPTICAL", "BIKE", "RESISTANCE_BAND","YOGA", "MAT", "FOAM_ROLLER",
    "FOOTBALL", "BASKETBALL", "BASEBALL", "SOCCER",
    "CRICKET", "TENNIS", "VOLLEYBALL", "RUGBY","GOLF", "HOCKEY", "BADMINTON",
    "CAMPING", "HIKING", "CLIMBING", "FISHING",
    "HUNTING", "CYCLING", "BICYCLE", "SKATE","SKATEBOARD", "SKI", "SNOWBOARD",
    "HELMET", "KNEE_PAD", "ELBOW_PAD",
    "GLOVES", "MOUTHGUARD", "SHIN_GUARD","SPORTS_BAG", "GYM_BAG", "WATER_BOTTLE",
    "FITNESS_TRACKER", "STEP_COUNTER","AIMING_SCOPE_SIGHT", "PROJECTILE_BOW", "AIR_GUN",
    "AIR_GUN_PROJECTILE", "IMPACT_PROTECTION_GEAR",
    "JUMP_ROPE","HAND_STRENGTHENER","SLEEPING_BAG","BALANCE_BOARD","TRAMPOLINE",
    "HYDRATION_PACK","SNORKELING_SET","PUNCHING_BAG","SWIM_CAP","TRACTION_CLEAT",
    "PERSONAL_FLOTATION_DEVICE","CALISTHENICS_STAND","KITE","SWIM_FIN","SLED",
    "KAYAK","PADDLEBOARD","AGILITY_LADDER"
]
pattern = "|".join(sports_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Sports"

#### Health

In [49]:
health_keywords = [
    "HEALTH", "WELLNESS", "MEDICAL", "THERAPY","TREATMENT", "CARE", "FIRST_AID",
    "VITAMIN", "MINERAL", "SUPPLEMENT","PROBIOTIC", "OMEGA", "FISH_OIL",
    "MULTIVITAMIN", "CALCIUM", "IRON","MAGNESIUM", "ZINC", "HERBAL",
    "IMMUNITY", "COLLAGEN", "PROTEIN","THERMOMETER", "BLOOD_PRESSURE",
    "GLUCOSE", "BLOOD_SUGAR","OXYGEN", "PULSE", "NEBULIZER",
    "INHALER", "MONITOR","BRACE", "ORTHOPEDIC", "SUPPORT",
    "BANDAGE", "GAUZE", "PATCH","HOT_PACK", "COLD_PACK",
    "MASSAGER", "TENS","MASK", "SANITIZER", "DISINFECTANT",
    "INCONTINENCE", "MEDICAL_GLOVE","CONDOM", "PREGNANCY_TEST",
    "SLEEP_AID", "MELATONIN", "STRESS_RELIEF","WEIGH_SCALE",
    "ORTHOPEDIC_BRACE","MASSAGER", "INCONTINENCE_PROTECTOR",
    "RESPIRATOR","THERAPEUTIC_THERMAL_COMPRESS","TAMPON",
    "MOUTH_GUARD","ENEMA_DOUCHE","WALKER","BLOOD_LANCET","DAILY_LIVING_AIDS",
    "CONTACT_LENSES","EARMUFF", "EARPLUG", "SELF_DEFENSE_SPRAY", "BODY_STRAP"
]

pattern = "|".join(health_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Health"

#### Pet

In [50]:
pet_keywords = [
    "PET", "PET_SUPPLY", "PET_PRODUCT",
    "DOG", "PUPPY", "CAT", "KITTEN","ANIMAL",
    "BIRD", "PARROT", "FISH", "AQUARIUM",
    "REPTILE", "HAMSTER", "RABBIT",
    "PET_FOOD", "DOG_FOOD", "CAT_FOOD",
    "TREAT", "KIBBLE", "WET_FOOD",
    "LEASH", "COLLAR", "HARNESS",
    "PET_BED", "CAGE", "CRATE",
    "LITTER", "SCRATCHER",
    "FEEDER", "WATER_BOWL",
    "PET_SHAMPOO", "GROOMING",
    "BRUSH", "PET_BRUSH",
    "NAIL_TRIMMER","PAW_HOOF_PROTECTOR", "HORSE_TACK_EQUIPMENT",
    "FLEA", "TICK", "PET_VITAMIN",
    "PET_SUPPLEMENT",
    "PET_TOY", "CHEW_TOY",
    "BALL", "ROPE_TOY"
]

pattern = "|".join(pet_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Pet_Supplies"

#### Toys

In [51]:
toys_keywords = [
    "TOY", "TOYS", "PLAY", "PLAYSET","ACTION_FIGURE", "FIGURE", "DOLL",
    "BARBIE", "SUPERHERO", "MODEL_KIT","BOARD_GAME", "CARD_GAME",
    "PUZZLE", "JIGSAW","EDUCATIONAL_TOY", "LEARNING",
    "STEM_TOY", "BUILDING_BLOCK","BLOCK", "LEGO",
    "RIDE_ON", "SCOOTER","RC", "REMOTE_CONTROL",
    "DRONE_TOY","INFANT_TOY", "BABY_TOY",
    "PLUSH", "STUFFED","CRAFT_KIT","SLIME", "COLORING",
    "PAINT_SET","BUBBLE_MAKER","YO_YO","PINATA","SANDBOX","MODEL"
]
pattern = "|".join(toys_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Toys"

#### Art_Supplies

In [52]:
arts_keywords = [
    "YARN", "CRAFT_BEAD", "CRAFT_MOLD", "CROCHET_HOOK",
    "PIPING_TIP", "SEWING_PATTERN", "PRESSER_FOOT","ART",
    "THREAD_CORD", "FABRIC", "CRAFT_EYE", "CONFETTI", "ART_KIT"
]
pattern = "|".join(arts_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Art_Supplies"

#### Books

In [53]:
books_keywords = [
    "BOOK", "BOOKS", "EBOOK", "E-BOOK",
    "HARDCOVER", "PAPERBACK",
    "TEXTBOOK", "WORKBOOK", "STUDY_GUIDE",
    "EXAM_PREP", "REFERENCE_BOOK",
    "NOVEL", "FICTION", "NONFICTION",
    "BIOGRAPHY", "AUTOBIOGRAPHY",
    "MEMOIR", "POETRY",
    "CHILDREN_BOOK", "STORYBOOK",
    "COLORING_BOOK", "ACTIVITY_BOOK",
    "COMIC", "MANGA", "GRAPHIC_NOVEL",
    "BIBLE", "RELIGIOUS_BOOK",
    "SELF_HELP", "MOTIVATIONAL_BOOK",
    "MAGAZINE", "JOURNAL", "PERIODICAL"
]
pattern = "|".join(books_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Books"

#### Automotive

In [54]:
automotive_keywords = [
    "AUTOMOTIVE", "AUTO", "VEHICLE", "CAR", "TRUCK", "SUV",
    "MOTORCYCLE", "BIKE_PART","ENGINE", "BRAKE", "TIRE", "TYRE", "WHEEL",
    "BATTERY", "SPARK_PLUG", "FILTER","HEADLIGHT", "TAILLIGHT", "MIRROR",
    "BUMPER", "RADIATOR", "EXHAUST","MOTOR_OIL", "ENGINE_OIL", "COOLANT",
    "CAR_WASH", "WAX", "POLISH","CAR_CLEANER", "DETAILING",
    "CAR_ACCESSORY", "SEAT_COVER","FLOOR_MAT", "CAR_MAT","CAR_COVER", "DASHCAM",
    "GPS", "CAR_CHARGER","JACK", "JUMPER_CABLE","TOOL_KIT", "TIRE_INFLATOR",
    "AIR_PUMP", "EMERGENCY_KIT","WIPER_BLADE","TRAILER_HITCH_COVER",
    "TOW_HITCH","MUFFLER","TONNEAU_COVER","IGNITION_COIL","SHOCK_ABSORBER",
    "WINDSHIELD_SNOW_COVER","FUEL_INJECTOR"
]

pattern = "|".join(automotive_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Automotive"

#### Office Supplies

In [55]:
office_keywords = [
    "OFFICE", "STATIONERY", "SUPPLIES",
    "PEN", "PENCIL", "MARKER", "HIGHLIGHTER",
    "ERASER", "SHARPENER", "INK", "REFILL",
    "PAPER", "NOTEBOOK", "NOTEPAD",
    "LEGAL_PAD", "PRINTING_PAPER",
    "ENVELOPE", "LABEL", "STICKER",
    "FOLDER", "BINDER", "FILE",
    "CLIP", "STAPLE", "STAPLER",
    "PAPER_CLIP", "PUSH_PIN",
    "DESK_ORGANIZER","SIGNAGE",
    "CALCULATOR", "DESK_PAD",
    "WHITEBOARD", "NOTICE_BOARD",
    "BULLETIN_BOARD",
    "PACKING_TAPE", "ADHESIVE_TAPE",
    "SHIPPING_LABEL", "BUBBLE_MAILER",
    "SHREDDER", "LAMINATOR",
    "PROJECTOR_SCREEN","WRITING_INSTRUMENT",
    "PLANNER","LABEL","STICKER_DECAL","WRITING_BOARD", "RULER", "HOLE_PUNCH",
    "BADGE_HOLDER", "MAPS",
    "ADHESIVE_TAPES","GIFT_WRAP","BANNER"
]

pattern = "|".join(office_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Office_Supplies"

#### Baby

In [56]:
baby_keywords = [
    "BABY", "INFANT", "TODDLER", "NEWBORN",
    "DIAPER", "NAPPY", "WIPES",
    "DIAPER_BAG", "CHANGING_PAD",
    "INCONTINENCE_PROTECTOR",
    "BABY_BOTTLE", "FEEDING_BOTTLE",
    "PACIFIER", "TEETHER",
    "BABY_FORMULA", "BREAST_PUMP",
    "BIB", "SIPPY_CUP",
    "BABY_FOOD", "PUREE",
    "STROLLER", "CAR_SEAT",
    "CRIB", "BASSINET",
    "HIGH_CHAIR", "PLAYPEN",
    "BABY_MONITOR",
    "ONESIE", "BABY_WEAR",
    "INFANT_CLOTHING",
    "BABY_LOTION", "BABY_SHAMPOO",
    "BABY_OIL", "BABY_POWDER",
    "NASAL_ASPIRATOR",
    "BABY_THERMOMETER",
    "SAFETY_GATE", "CORNER_GUARD",
    "OUTLET_COVER",
    "RATTLE", "BABY_TOY",
    "PLUSH_TOY"
]

pattern = "|".join(baby_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Baby"

#### Music and Media

In [57]:
music_media_keywords = [
    "MUSIC", "MEDIA", "ENTERTAINMENT","CD", "AUDIO_CD", "VINYL", "RECORD",
    "CASSETTE", "ALBUM", "PHYSICAL_MOVIE","DVD", "BLU_RAY", "BLURAY",
    "MOVIE", "FILM","PHYSICAL_MOVIE","DIGITAL_DOWNLOAD","STREAMING_MEDIA",
    "GUITAR", "PIANO", "KEYBOARD_INSTRUMENT","DRUM", "VIOLIN", "UKULELE",
    "FLUTE", "SAXOPHONE", "TRUMPET","AMPLIFIER", "AUDIO_PLAYER",
    "RECORD_PLAYER","GUITAR_STRINGS", "DRUM_STICKS","INSTRUMENT_CASE",
    "SHEET_MUSIC", "PLECTRUM","CAPO",
    "MISC_WORLD_INSTRUMENTS"
]
pattern = "|".join(music_media_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Music_and_Media"

#### Luggage and Travel

In [58]:
luggage_travel_keywords = [
    "LUGGAGE", "TRAVEL", "SUITCASE",
    "TRAVEL_BAG", "DUFFEL", "DUFFLE",
    "CARRY_ON", "CABIN_BAG",
    "WEEKENDER", "TROLLEY_BAG",
    "BACKPACK", "TRAVEL_BACKPACK",
    "LAPTOP_BAG","BAG",
    "PACKING_CUBE", "TRAVEL_ORGANIZER",
    "TOILETRY_BAG", "GARMENT_BAG",
    "PASSPORT_HOLDER", "LUGGAGE_TAG",
    "TRAVEL_PILLOW", "NECK_PILLOW",
    "EYE_MASK", "SLEEP_MASK",
    "TRAVEL_ADAPTER",
    "LUGGAGE_LOCK", "TSA_LOCK",
    "TRAVEL_SCALE", "PORTABLE_STEAMER"
]
pattern = "|".join(luggage_travel_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Luggage_and_Travel"

#### Garden and Outdoor

In [59]:
garden_outdoor_keywords = [
    "GARDEN", "OUTDOOR", "YARD", "LAWN", "PATIO","PLANT", "SEED", "SOIL", "FERTILIZER",
    "COMPOST", "PLANTER", "POT","FLOWER", "HERB", "SHRUB",
    "SHOVEL", "RAKE", "HOE", "PRUNER","GARDEN_TOOL", "WATERING_CAN",
    "HOSE", "SPRINKLER", "TRIMMER","LAWN_MOWER", "HEDGE_TRIMMER",
    "OUTDOOR_FURNITURE", "PATIO_SET","UMBRELLA", "HAMMOCK",
    "GRILL", "BARBECUE", "BBQ","FIRE_PIT","PAINT",
    "OUTDOOR_LIGHT", "SOLAR_LIGHT","STRING_LIGHT","GARDEN_DECOR", "BIRD_FEEDER",
    "BIRD_BATH","INSECT_REPELLENT","ICE_CHEST","TARP","TENT","NETTING_COVER","SPLASH_POOL","WREATH",
    "POOL_COVER","PRESSURE_WASHER","SHADE_SAIL","GREENHOUSE","PICNIC_HOLDER","SWIMMING_POOL","CISTERN",
    "SNOW_BLOWER","HOT_TUB","IRRIGATION_EQUIPMENT","POOL_HEATER","SAUNA","DRIP_IRRIGATION_KIT", "LEAF_BLOWER", "FREESTANDING_SHELTER",
    "SURVIVAL_KIT", "NAVIGATION_COMPASS", "WHISTLE"
]
pattern = "|".join(garden_outdoor_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Garden_and_Outdoor"

#### Industrial

In [60]:
industrial_keywords = [
    "INDUSTRIAL", "COMMERCIAL", "HEAVY_DUTY","MANUFACTURING", "FACTORY", "WAREHOUSE",
    "MACHINE", "MACHINERY", "GENERATOR","COMPRESSOR", "PUMP", "MOTOR","RACK",
    "CONVEYOR", "DRILL_PRESS","TAPE_MEASURE","WELDER", "WELDING", "CUTTER","STEP_STOOL",
    "GRINDER", "LATHE", "CNC","HYDRAULIC", "PNEUMATIC",
    "BEARING", "VALVE", "PIPE","FITTING", "FASTENER", "BOLT",
    "NUT", "SCREW", "GASKET","INDUSTRIAL_SWITCH", "CIRCUIT_BREAKER",
    "TRANSFORMER", "CONTROL_PANEL","INDUSTRIAL_CABLE",
    "HARD_HAT", "SAFETY_VEST","STEEL_TOE", "WORK_GLOVE",
    "SAFETY_GOGGLE", "PROTECTIVE_GEAR","CALIPER", "MICROMETER",
    "GAUGE", "METER","MEASURING_TOOL","THERMOPLASTIC_FILAMENT",
    "LAB_SUPPLY","SCIENCE_FUNDAMENTALS_KIT","LAB_SUPPLY_TUBE",
    "PROTOTYPING_BOARD","FIXED_RESISTOR","TRANSISTOR","ZENER_DIODE",
    "RESISTOR","METALS","PLASTICS","END_MILLS","TOOL_BELT", "TOOL_CHUCK", "HANDLE_GRIP",
    "HEAT_PRESS", "HOT_MELT", "IMMERSION_HEATER"
]
pattern = "|".join(industrial_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Industrial"

#### Hardware

In [61]:
hardware_keywords = [
    "HARDWARE", "HOME_IMPROVEMENT", "DIY","HAMMER", "SCREWDRIVER", "WRENCH","PLIERS", "SAW", "DRILL",
    "TOOL_SET", "TOOL_KIT","NAIL", "SCREW", "BOLT","NUT", "ANCHOR", "FASTENER",
    "LUMBER", "WOOD_BOARD","PLYWOOD", "DRYWALL","CEMENT", "CONCRETE","ADHESIVE", "GLUE",
    "CAULK", "SEALANT","PAINT", "PRIMER","BRUSH", "ROLLER","SANDPAPER","BONDING_ADHESIVES",
    "FAUCET", "PIPE","PLUMBING", "VALVE","DRAIN", "SHOWER_HEAD","SWITCH", "OUTLET",
    "LIGHT_BULB","EXTENSION_CORD","POWER_STRIP","DOOR_HANDLE", "HINGE","LOCK", "CABINET_HANDLE",
    "MECHANICAL_COMPONENTS","MULTITOOL","CRAFT_WOOD","SHARP_PIN","TEMPORARY_GATE",
    "SHIPPING_BOX","RUBBER_STAMP","DUST_REMOVAL_TOOL","WEATHER_STRIPPING","MECHANICAL_BELT","SAFE","WIRE",
    "UTILITY_MAGNET","CORD_ROPE","KNITTING_NEEDLE","HAND_SEWING_NEEDLE","FUSE","SEWING_BUTTON",
    "WASHERS","ROTARY_TOOL","SANDER","LADDER","AXE","CHISEL","HANDRAIL","LEVEL","WIRE_STRIPPER",
    "INSULATION","GREASE_GUN","METAL_TUBING","SEALS","PUNCH_TOOL","RIVET","PULLEYS","SPROCKETS","THREADING_TAPS","THREADING_DIES",
    "FIRE_GRATE","PICTURE_HANGER", "DOOR", "TILE", "BUCKLE","GROMMETS", "FLEXIBLE_COUPLINGS", "FLEXIBLE_MAGNET",
    "PLASTIC_TUBING", "TEMPORARY_HANGER_HOOK"
]
pattern = "|".join(hardware_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Hardware"

#### Jewelry

In [62]:
jewelry_keywords = [
    "JEWELRY", "JEWELLERY", "ACCESSORY",
    "RING", "ENGAGEMENT_RING", "WEDDING_RING",
    "BAND",
    "NECKLACE", "PENDANT", "CHAIN",
    "BRACELET", "BANGLE",
    "EARRING", "STUD", "HOOP",
    "ANKLET", "BODY_JEWELRY",
    "WATCH", "WRISTWATCH",
    "GOLD", "SILVER", "PLATINUM",
    "DIAMOND", "GEMSTONE", "PEARL",
    "CHARM", "BROOCH", "CUFFLINK"
]
pattern = "|".join(jewelry_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Jewelry"

#### Software

In [63]:
software_keywords = [
    "SOFTWARE", "PROGRAM", "APPLICATION", "APP",
    "DIGITAL_LICENSE", "LICENSE_KEY",
    "WINDOWS", "MACOS", "LINUX",
    "OPERATING_SYSTEM", "OS",
    "OFFICE_SUITE", "WORD_PROCESSOR",
    "SPREADSHEET", "PRESENTATION_SOFTWARE",
    "PDF_EDITOR",
    "ANTIVIRUS", "SECURITY_SOFTWARE",
    "FIREWALL", "VPN",
    "PHOTO_EDITING", "VIDEO_EDITING",
    "DESIGN_SOFTWARE", "CAD_SOFTWARE",
    "IDE", "DEVELOPER_TOOL",
    "PROGRAMMING_SOFTWARE",
    "ACCOUNTING_SOFTWARE", "ERP",
    "CRM_SOFTWARE", "PROJECT_MANAGEMENT",
    "GAME_DOWNLOAD", "DIGITAL_GAME",
    "GAME_LICENSE",
    "BACKUP_SOFTWARE", "DRIVER",
    "SYSTEM_TOOL"
]
pattern = "|".join(software_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Software"

#### Kitchen

In [64]:
kitchen_keywords = [
    "KITCHEN", "COOKWARE", "DINING","PAN", "POT", "SKILLET", "SAUCEPAN",
    "PRESSURE_COOKER", "WOK","SLOW_COOKER",
    "BAKING_TRAY", "BAKEWARE","FLASK","SPATULA", "LADLE", "TONGS",
    "WHISK", "KNIFE", "FORK","DEEP_FRYER",
    "SPOON", "CUTLERY","BOILERS","BLENDER", "MIXER", "TOASTER",
    "COFFEE_MAKER", "KETTLE","AIR_FRYER", "RICE_COOKER",
    "FOOD_PROCESSOR", "MICROWAVE","CONTAINER", "FOOD_STORAGE",
    "LUNCH_BOX", "JAR","CANISTER","DINNERWARE",
    "PLATE", "BOWL", "CUP","GLASS", "MUG","CUTTING_BOARD",
    "SERVING_TRAY","DISH_RACK", "DISH_BRUSH","DISH_CLOTH","MEAL_HOLDER",
    "FLATWARE","PITCHER","FUNNEL","CASSEROLES","ROLLING_PIN", "SERVEWARE",
    "GARLIC_PRESS", "ICE_MAKER","CORE_PIT_REMOVER","TRIVET","MORTAR_AND_PESTLE_SET",
    "SKEWER","SALAD_SPINNER","VENT_HOOD","RANGE","MESS_KIT"
]
pattern = "|".join(kitchen_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Kitchen"

#### Household Essentials

In [65]:
household_keywords = [
    "HOUSEHOLD", "HOME_CARE", "CLEANING_SUPPLY","BOTTLE",
    "CLEANER", "DISINFECTANT", "BLEACH","FLOOR_CLEANER", "GLASS_CLEANER",
    "SURFACE_CLEANER", "TOILET_CLEANER","CANNED_AIR","DENT_REMOVAL_TOOL",
    "SCRUBBER", "SPONGE", "CLEANING_BRUSH","LAUNDRY", "DETERGENT",
    "FABRIC_SOFTENER", "STAIN_REMOVER","DRYER_SHEET", "CLEANING_AGENT",
    "SKIN_CLEANING_AGENT","LAUNDRY_DETERGENT",
    "WASTE_BAG","CLEANING_BRUSH","SAFETY_MASK","HVAC_AIR_FILTER",
    "PAPER_TOWEL", "TISSUE","TOILET_PAPER", "NAPKIN","AIR_COOLER", "HEATING_STOVE", "INCUBATOR",
    "AIR_FRESHENER", "AREA_DEODORIZER","ODOR_ELIMINATOR", "SCENTED_CANDLE",
    "TRASH_BAG", "GARBAGE_BAG","WASTE_BAG", "STORAGE_BAG","PEST_CONTROL", "INSECT_SPRAY",
    "MOSQUITO_REPELLENT","ICE_CUBE_TRAY","BATTERY_HOME_USE", "MATCHBOX","CALENDAR","DRYING_RACK",
    "ALUMINUM_FOIL", "CLING_WRAP","SCISSORS","TRASH_CAN","HANGING_ROD","LINT_REMOVER",
    "AROMA_DIFFUSER","AIR_PURIFIER","HUMIDIFIER","TEXTILE_DEODORIZER","GAS_SMOKE_FIRE_ALARM",
    "SPACE_HEATER","DEHUMIDIFIER","BROOM","MOP","MOP_BUCKET_SET","JANITORIAL_SUPPLY",
    "BUCKET","TRASH_COMPACTOR","ITEM_STAND", "FOOT_SCRAPER", "SQUEEGEE", "FOOTREST",
    "TIMER", "WRIST_REST", "PINBOARD", "MONEY_BANK","WIND_SPINNER", "STORE_FIXTURES_AND_EQUIPMENT"
]
pattern = "|".join(household_keywords)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Household_Essentials"

#### Services

In [66]:
services = [
    "CONSUMER_SERVICES_SUBSCRIPTION",
    "INSTALLATION_SERVICES",
    "WIRELESS_SERVICE_PLAN",
    "KINDLE_UNLIMITED_MEMBERSHIP"
]

pattern = "|".join(services)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Services"

#### Collectibles

In [67]:
collectibles = [
    "COLLECTIBLE_COINS",
    "BULLION",
    "COLLECTIBLES",
    "HISTORICAL_COLLECTIBLES",
    "STAMPS"
]
pattern = "|".join(collectibles)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Collectibles"

#### Optical

In [68]:
optical_equipment = [
    "MAGNIFIER", "BINOCULAR", "TELESCOPE", "METAL_DETECTOR"
]
pattern = "|".join(optical_equipment)
mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Optical"

#### Misc

In [69]:
misc = [
    "PRIME",
    "BISS",
    "MISC_OTHER",
    "Misc.",
    "PRODUCT",
    "PROTECTED_COLLECTION",
    "GIFT_XXRD","GIFTS",
    "FINEOTHER","HOBBIES", "Misc", "Services",
    "Collectibles", "GUILD_ACCESSORIES",
    "WINDING_REEL", "WASHER"
]
pattern = "|".join(misc)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Misc"

#### Fuel

In [70]:
fuel_fire_accessories = [
    "SOLID_FIRE_FUEL",
    "FLAME_WICK"
]
pattern = "|".join(fuel_fire_accessories)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Fuel"

#### Weapons

In [71]:
weapon_accessories = [
    "GUN_HOLSTER",
    "WEAPON_CASE",
    "GUN_SLING",
    "GUN_GRIP", "SWORD"
]
pattern = "|".join(weapon_accessories)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Weapons"

#### Smoking

In [72]:
smoking_accessories = [
    "CIGARETTE_CASE",
    "HOOKAH",
    "HUMIDOR"
]
pattern = "|".join(smoking_accessories)


mask = combined["Category"].str.contains(pattern, case=False, na=False)
combined.loc[mask, "Category"] = "Smoking"

In [73]:
combined.shape

(1839075, 34)

In [74]:
combined.isna().sum()

User_ID                      0
Product ID                   0
Category                     0
Title                        0
Quantity                     0
Purchase Price Per Unit      0
State_x                      0
Duplicate                    0
Brand                      982
Year                         0
Month                        0
Day                          0
Age                          0
Hispanic                     0
Race                         0
Education                    0
Income                       0
Gender                       0
Sexual_Orientation           0
State_y                      0
No.of Users                  0
Family Size                  0
Acc Usage                    0
Cigarettes                   0
Marijuana                    0
Alcohol                      0
Diabetes                     0
Wheel_Chair                  0
Life_Changes                 0
Sell_Data                    0
Sell_Consumer_Data           0
Small_Business_Use           0
Census_Use                   0
Research                     0
dtype: int64

In [75]:
combined.nunique()

User_ID                      5026
Product ID                 939073
Category                       26
Title                      824711
Quantity                       69
Purchase Price Per Unit     18282
State_x                        53
Duplicate                       2
Brand                      388011
Year                            6
Month                          12
Day                            31
Age                             6
Hispanic                        2
Race                           25
Education                       5
Income                          7
Gender                          4
Sexual_Orientation              3
State_y                        52
No.of Users                     4
Family Size                     4
Acc Usage                       3
Cigarettes                      4
Marijuana                       4
Alcohol                         4
Diabetes                        3
Wheel_Chair                     3
Life_Changes                   23
Sell_Data                       4
Sell_Consumer_Data              4
Small_Business_Use              3
Census_Use                      3
Research                        3
dtype: int64

In [76]:
combined.to_csv(
    r"C:\Users\vaish\Desktop\MKT 4990\Merged_Cleaned_final_dataset.csv"
)

In [78]:
combined.head()

,User_ID,Product ID,Category,Title,Quantity,Purchase Price Per Unit,State_x,Duplicate,Brand,Year,...,Marijuana,Alcohol,Diabetes,Wheel_Chair,Life_Changes,Sell_Data,Sell_Consumer_Data,Small_Business_Use,Census_Use,Research
0,R_01vNIayewjIIKMF,B0143RTB1E,Electronics,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,1.0,7.98,NJ,No,SanDisk Ultra,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
1,R_01vNIayewjIIKMF,B01MA1MJ6H,Electronics,Betron BS10 Earphones Wired Headphones in Ear ...,1.0,13.99,NJ,No,Betron BS10,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
2,R_01vNIayewjIIKMF,B078JZTFN3,Unknown,Unknown,1.0,8.99,NJ,No,unknown,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
3,R_01vNIayewjIIKMF,B06XWF9HML,Home-Bed-Bath,Perfecto Stainless Steel Shaving Bowl. Durable...,1.0,10.45,NJ,No,Perfecto Stainless,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
4,R_01vNIayewjIIKMF,B00837ZOI0,Beauty,Proraso Shaving Cream for Men,1.0,10.00,NJ,No,Proraso Shaving,2018,...,No,No,No,No,N/A,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes

In [79]:
combined['Product ID'].nunique()

939073

In [80]:
combined.shape

(1839075, 34)

### Visualizations

In [ ]:
unique_category_1

In [ ]:
plt.figure()
plt.bar(unique_category_1.index, unique_category_1.values)
plt.xticks(rotation=90)
plt.xlabel("Category")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

In [ ]:
unique_category_1.shape